[project]
name = "mlforterraingeneration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.0",
    "noise>=1.2.2",
    "pylandstats>=3.0.3",
    "seaborn>=0.13.2",
]
